// USB ID 1209:ACC1 allocated by pidcodes.github.com
USB_VID = 0x1209
USB_PID = 0xACC1

USB_PRODUCT = "Redsoil"
USB_MANUFACTURER = "Accelerando"

MCU_CHIP = nrf52840

INTERNAL_FLASH_FILESYSTEM = 1

MICROPY_PY_ASYNC_AWAIT = 0
